// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: speakers.proto

package speakers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AudioOutputClient is the client API for AudioOutput service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioOutputClient interface {
	Play(ctx context.Context, in *Audio, opts ...grpc.CallOption) (*Audio, error)
}

type audioOutputClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioOutputClient(cc grpc.ClientConnInterface) AudioOutputClient {
	return &audioOutputClient{cc}
}

func (c *audioOutputClient) Play(ctx context.Context, in *Audio, opts ...grpc.CallOption) (*Audio, error) {
	out := new(Audio)
	err := c.cc.Invoke(ctx, "/speakers.AudioOutput/Play", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioOutputServer is the server API for AudioOutput service.
// All implementations must embed UnimplementedAudioOutputServer
// for forward compatibility
type AudioOutputServer interface {
	Play(context.Context, *Audio) (*Audio, error)
	mustEmbedUnimplementedAudioOutputServer()
}

// UnimplementedAudioOutputServer must be embedded to have forward compatible implementations.
type UnimplementedAudioOutputServer struct {
}

func (UnimplementedAudioOutputServer) Play(context.Context, *Audio) (*Audio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedAudioOutputServer) mustEmbedUnimplementedAudioOutputServer() {}

// UnsafeAudioOutputServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioOutputServer will
// result in compilation errors.
type UnsafeAudioOutputServer interface {
	mustEmbedUnimplementedAudioOutputServer()
}

func RegisterAudioOutputServer(s grpc.ServiceRegistrar, srv AudioOutputServer) {
	s.RegisterService(&AudioOutput_ServiceDesc, srv)
}

func _AudioOutput_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Audio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioOutputServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/speakers.AudioOutput/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioOutputServer).Play(ctx, req.(*Audio))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioOutput_ServiceDesc is the grpc.ServiceDesc for AudioOutput service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioOutput_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speakers.AudioOutput",
	HandlerType: (*AudioOutputServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Play",
			Handler:    _AudioOutput_Play_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speakers.proto",
}
